# Generated by Django 4.1.4 on 2023-05-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_first_name_user_last_name_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
