# Generated by Django 4.1.4 on 2023-05-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
